os: linux
dist: focal
language: python
python:
  - "3.7"

env:
  global:
    - secure: HHnMQ7VoiKGWaF8iu5tWylcwsZwDdYSHXrZeq8N31JWuxINI+bBxgrlkr0rvpfoYNgoh0aVGBqCIO9W5fkvjxQDgVPkJILnjC4+5MP2W8oYK7+vXMzLs3y0GX6IfPaHmNTtAL48YH0RSXJNKPr7kwxqOEZ2xNUBTLz+FOm2WI3O1c1Oub0zGWg8wWrOLNrNmGEv5r3guLjw5efGMuDxwWJV7myLs63jaVq6wqXTLe5Go7uMTaeAp/jK2TGfkKAx1iMx8kKdtGuYoK2F0q4FnUjbglxXMoTa8DXgJgGkhfZTFqWrBqkyXogIhczD2nCtFrqRB6N/t8Pe4jCnCbpaWFoibtJe8t8PaZTTwDdlt7JeQncYNnn1MxR4auU1iAg7pIjilKJu6xMQHxmhpHmVFA8CS0+rwb6OM8SggpeHBN8s10d+kmepUXFU0luOko6cfOaJWiIBmfgWj6ZmO+CA3crpDUMqwqTBBxZYs9J9Q2NDcE9jor0jPk5kKQ91AWL4yLSHUhx0fpXCXd9dAr2iS7FU9+1gYjaOi7/BswIQ5i98bv93Ni2h5Qzl2p9AohA/vHU5D1h8XvuU22AjkTYyKuI6n6DGnICVdA0s8CQlK3YjvCPW2/NGzmCRGGs12tGaUMasZvntmAJCEH/Tak+fll1ZaDmkVZbDHrKQg2Qbtmyk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master
    - TZ:       Africa/Johannesburg
    - PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/.dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

jobs:
  fast_finish: true

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install domain2idna
  - pip3 install PyFunceble-dev --pre
  - pip3 install ultimate-hosts-blacklist-whitelist-dev --pre
  #-

script:
  - bash .dev-tools/pre-deploy.sh

notifications:
  on_success:   change
  on_failure:   always
